src/Directory.Packages.props
src/OneGround.ZGW.Common.Web/Filters/ETagFilter.cs
src/OneGround.ZGW.Common.Web/ZGW.Common.Web.csproj

Etag improvements. Fixed  issue with contentlenght

---

src/OneGround.ZGW.Common.ServiceAgent/Caching/CachingConfiguration.cs
src/OneGround.ZGW.Common/Caching/CacheEntity.cs

FUND-928 ZRC Casetype can be appended with random text when creating a case

---

src/OneGround.ZGW.Common.Web/Extensions/ServiceCollection/ZGWApiServiceCollectionExtensions.cs
src/appsettings.Shared.json

Added Possibility to Configure Forwarded Headers Trusts

---

src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/PublishBesluitTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/PublishInformatieObjectTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/PublishZaakTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/PublishBesluitTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/PublishInformatieObjectTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/PublishZaakTypeCommandHandler.cs

FUND-1500 When publishing a casetype/IOT/DT the check considers all catalogs

---

src/OneGround.ZGW.DataAccess/DatabaseInitializer.cs
src/OneGround.ZGW.DataAccess/DatabaseVerifier.cs

ReloadTypes after applying migrations is no longer needed after npgsql update. Service would crash on first startup, because connection was already open. This is now handled by npgsql.

FUND-1777 Remove ReloadTypes after applying migrations

---

src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/UpdateInformatieObjectTypeCommandHandler.cs

FUND-1807 ZTC Patching of published information object types created with older ztc version fails

---

src/OneGround.ZGW.Besluiten.Web/Validators/BesluitRequestValidator.cs
src/OneGround.ZGW.Common.Web/Validations/IRuleBuilderExtensions.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/1/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/5/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Zaken.Web/Validators/v1/5/ZaakRequestValidator.cs
src/OneGround.ZGW.Zaken.Web/Validators/v1/ZaakRequestValidator.cs

FUND-1606 ZRC. BRC DRC: add catalogus_id to besluit, zaak and eio (extra validation creating objects)

---

src/OneGround.ZGW.Besluiten.Web/MappingProfiles/v1/RequestToDomainProfile.cs
src/OneGround.ZGW.Besluiten.Web/Validators/BesluitRequestValidator.cs
src/OneGround.ZGW.Common.Web/Validations/IRuleBuilderExtensions.cs
src/OneGround.ZGW.Documenten.Web/MappingProfiles/v1/1/RequestToDomainProfile.cs
src/OneGround.ZGW.Documenten.Web/MappingProfiles/v1/5/RequestToDomainProfile.cs
src/OneGround.ZGW.Documenten.Web/MappingProfiles/v1/RequestToDomainProfile.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/1/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/5/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Documenten.Web/Validators/v1/EnkelvoudigInformatieObjectRequestValidator.cs
src/OneGround.ZGW.Zaken.Web/MappingProfiles/v1/5/RequestToDomainProfile.cs
src/OneGround.ZGW.Zaken.Web/MappingProfiles/v1/RequestToDomainProfile.cs
src/OneGround.ZGW.Zaken.Web/Validators/v1/5/ZaakRequestValidator.cs
src/OneGround.ZGW.Zaken.Web/Validators/v1/ZaakRequestValidator.cs

FUND-1606 rollback changes and fix on another way preventing storing types with ending slash

---

src/OneGround.ZGW.Catalogi.DataModel/BrondatumArchiefProcedure .cs
src/OneGround.ZGW.Catalogi.DataModel/Migrations/20250626083431_add_owner_fields_to_some_ztc_tables.Designer.cs
src/OneGround.ZGW.Catalogi.DataModel/Migrations/20250626083431_add_owner_fields_to_some_ztc_tables.cs
src/OneGround.ZGW.Catalogi.DataModel/ReferentieProces.cs
src/OneGround.ZGW.Catalogi.DataModel/ZaakTypeDeelZaakType.cs
src/OneGround.ZGW.Catalogi.DataModel/ZtcDbContext.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/CreateResultaatTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/CreateZaakTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/UpdateResultaatTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/UpdateZaakTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/CreateResultaatTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/CreateZaakTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/UpdateResultaatTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/UpdateZaakTypeCommandHandler.cs
src/OneGround.ZGW.Catalogi.Web/MappingProfiles/v1/RequestToDomainProfile.cs

FUND-1567 ZTC add field owner to tables ztc

---

src/OneGround.ZGW.Besluiten.DataModel/Besluit.cs
src/OneGround.ZGW.Besluiten.DataModel/Migrations/20250627060257_set_besluiten_column_catalogus_id_not_null.Designer.cs
src/OneGround.ZGW.Besluiten.DataModel/Migrations/20250627060257_set_besluiten_column_catalogus_id_not_null.cs
src/OneGround.ZGW.Documenten.DataModel/EnkelvoudigInformatieObject.cs
src/OneGround.ZGW.Documenten.DataModel/Migrations/20250627060444_set_documenten_column_catalogus_id_not_null.Designer.cs
src/OneGround.ZGW.Documenten.DataModel/Migrations/20250627060444_set_documenten_column_catalogus_id_not_null.cs
src/OneGround.ZGW.Zaken.DataModel/Migrations/20250627055620_set_zaken_column_catalogus_id_not_null.Designer.cs
src/OneGround.ZGW.Zaken.DataModel/Migrations/20250627055620_set_zaken_column_catalogus_id_not_null.cs
src/OneGround.ZGW.Zaken.DataModel/Zaak.cs

FUND-1606 Make column catalogus_id in zaken, besluiten and document NOT NULL

---

src/OneGround.ZGW.DataAccess/TemporaryTableProvider.cs

FUND-1823 Fixed Temporary Table DB Connection

---

src/OneGround.ZGW.Besluiten.Web/Handlers/v1/GetAllBesluitenQueryHandler.cs
src/OneGround.ZGW.Documenten.Web/Services/InformatieObjectAuthorizationTempTableService.cs
src/OneGround.ZGW.Zaken.Web/Services/ZaakAuthorizationTempTableService.cs

Handle duplicate Authorization Permissions for temp tables

FUND-1833 Handle duplicate Authorization Permissions for temp tables

---

src/OneGround.ZGW.Catalogi.Web/Controllers/v1/3/BesluitTypeController.cs
src/OneGround.ZGW.Catalogi.Web/Controllers/v1/3/ZaakTypeController.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/GetBesluitTypeQueryHandler.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/GetZaakTypeQueryHandler.cs
src/OneGround.ZGW.Catalogi.Web/MappingProfiles/v1/3/DomainToResponseProfile.cs
src/Tests/OneGround.ZGW.Common.Web.UnitTests/RequestMergerTests.cs

Fixed issues when patching **zakentypen** and **besluitypen** with soft relations
FUND-1855

FUND-1855 ZTC: Fixing patches for zakentypen and besluitypen with soft relations

---

.github/scripts/Get-NextApplicationVersion.ps1

- Revert validation helper method in Get-NextApplicationVersion script
FUND-1852

FUND-1852 - Fixed Get-NextApplicationVersion script

---

.github/workflows/cd-build-and-publish-image.yml

- fixed output variables
FUND-1852

FUND-1852 - Fixed CD build and publish image script

---

.github/workflows/cd-docker-hub-repository-update.yml
getting-started/docker-compose/.env
getting-started/docker-compose/README.md
getting-started/docker-compose/docker-compose.yml
localdev/.env
localdev/README.md
localdev/docker-compose.yml

- fixed HaProxy SSL certificate paths
- updated SSL certificate instalation steps
FUND-1738

FUND-1738 - Getting-started updates

---

src/OneGround.ZGW.Catalogi.Web/Handlers/v1/CreateInformatieObjectTypeCommandHandler.cs

ZTC 1.0 Set default value in InformatieObjectCategorie

---

src/OneGround.ZGW.Besluiten.Web/Expands/v1/BesluitInformatieObjectenExpander.cs
src/OneGround.ZGW.Besluiten.Web/Expands/v1/BesluitTypeExpander.cs
src/OneGround.ZGW.Besluiten.WebApi/appsettings.json
src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/CatalogiServiceAgent.cs
src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/ICatalogiServiceAgent.cs
src/OneGround.ZGW.Common/Caching/GenericCache.cs
src/OneGround.ZGW.Documenten.Web/Expands/v1/5/InformatieObjectExpander.cs
src/OneGround.ZGW.Documenten.Web/Expands/v1/5/InformatieObjectTypeExpander.cs
src/OneGround.ZGW.Documenten.WebApi/appsettings.json
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/HoofdZaakExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/RollenExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakBaseExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakContactmomentExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakInformatieObjectenExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakObjectenExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakResultaatExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakStatusExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakTypeExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZaakVerzoekenExpander.cs
src/OneGround.ZGW.Zaken.Web/Expands/v1/5/ZakenCollectionExpander.cs
src/OneGround.ZGW.Zaken.WebApi/appsettings.json

FUND-1930: Polly reconfig, async/await fixes and some other fixes

---

src/OneGround.ZGW.Notificaties.Messaging/Consumers/SendNotificatiesConsumer.cs

FUND-1998 NRC does not send kenmerk field transaction_id

---

src/OneGround.ZGW.Autorisaties.Common/BusinessRules/ApplicatieBusinessRuleService.cs
src/OneGround.ZGW.Besluiten.Web/Handlers/v1/CreateBesluitCommandHandler.cs
src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/CatalogiServiceAgent.cs
src/OneGround.ZGW.Catalogi.ServiceAgent/v1/CatalogiServiceAgent.cs
src/OneGround.ZGW.Catalogi.Web/Handlers/v1/3/Extensions/StatusTypeExensionMethods.cs
src/OneGround.ZGW.Common.ServiceAgent/ZGWServiceAgent.cs

…tters, numbers, and underscore.# Pull Request

Fixing Issues & Security Hotspots from SonarQube

---

getting-started/docker-compose/.env
getting-started/docker-compose/README.md
localdev/.env
localdev/README.md
localdev/haproxy/haproxy-localstack.cfg
src/OneGround.ZGW.Documenten.Messaging.Listener/Dockerfile
src/OneGround.ZGW.Documenten.Messaging.Listener/Program.cs
src/OneGround.ZGW.Documenten.Messaging.Listener/Properties/launchSettings.json
src/OneGround.ZGW.Documenten.Messaging.Listener/ZGW.Documenten.Messaging.Listener.csproj
src/OneGround.ZGW.Notificaties.Messaging.Listener/Dockerfile
src/OneGround.ZGW.Notificaties.Messaging.Listener/Program.cs
src/OneGround.ZGW.Notificaties.Messaging.Listener/Properties/launchSettings.json
src/OneGround.ZGW.Notificaties.Messaging.Listener/ZGW.Notificaties.Messaging.Listener.csproj

FUND-1570 NRC- and DRC-Listeners add health-check

---

src/OneGround.ZGW.Zaken.Web/Handlers/v1/5/CreateZaakObjectCommandHandler.cs
src/OneGround.ZGW.Zaken.Web/Handlers/v1/5/UpdateZaakObjectCommandHandler.cs

FUND-2001 ZRC 1.5 Create- and update zaakobject handlers should validate zaakobjecttype (ZTC 1.3)

---

src/OneGround.ZGW.Common.Web/Middleware/EnrichedLoggingMiddleware.cs

FUND-1762 Log ApiVersion header

---

src/OneGround.ZGW.Common/Helpers/TempFileHelper.cs
src/OneGround.ZGW.Documenten.Services.Ceph/CephDocumentServices.cs
src/Tests/OneGround.ZGW.Catalogi.WebApi.UnitTests/BusinessRulesTests/ConceptBusinessRulesTest.cs
src/Tests/OneGround.ZGW.Common.UnitTests/TempFileHelperTests.cs
src/Tests/OneGround.ZGW.Documenten.WebApi.UnitTests/BusinessRulesTests/v1/EnkelvoudigInformatieObjectBusinessRuleTests.cs

Improvements regarding Polaris scan
FUND-2081

FUND-2081 - Improvements regarding Polaris scan

---

src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/CatalogiServiceAgent.cs
src/OneGround.ZGW.Catalogi.ServiceAgent/v1/3/ICatalogiServiceAgent.cs

Expanded CatalogiServiceAgent, added  AddCatalogusAsync 
FUND-1494

FUND-1494 Added AddCatalogusAsync for CatalogiServiceAgent

---

tools/oneground-certificates-generator/Dockerfile
tools/oneground-certificates-generator/generate-oneground-certificates.sh

Changed Cert Generation Container Execution User
